export const AuthConstants = {
  CREATE_ACCOUNT: 'Create an account',
  LOG_IN: 'Log in to Exclusive',
  REGISTER: 'Register',
  LOG: 'Log In',
  SIGN_IN: 'Sign In',
  ENTER_DETAILS: 'Enter your details below',
  DONT_HAVE_AN_ACCOUNT: `Don't have an account?`,
  ALREADY_HAVE_AN_ACCOUNT: 'Already have account?',
  ORDER_PLACED: 'Your Order is Placed',
  CART_EMPTY: 'Your cart is empty',
  MY_CART: 'My Cart',
  PLACE_ORDER: 'Place Order',
  TOTAL: 'Total: $',
  INCRE_BUTTON: '+',
  DECRE_BUTTON: '-',
  TODAYS_FLASH_SALE: `Today's Flash Sales`,
  SUMMER_SALE_OFFER:
    'Summer Sale For All Swim Suits And Free Express Delivery - OFF 50%!',
  REVIEWS: 'reviews',
  EXCLUSIVE: 'Exclusive',
  HOME: 'Home',
  CONTACT: 'Contact',
  ABOUT: 'About',
  PRODUCT_NOT_FOUND: 'Product not found',
  GO_TO_CART: 'Go To Cart',
  BUY_NOW: 'Buy Now',
  SHOP_NOW: 'ShopNow',
};
